# Problem Set 0

$\textbf{Slicing}$

In [ ]:
x = [0,1,2,3,4,5] # Creates list
print(x[:2]) # Prints first two entries
print(x[2:]) # Prints last 4 entries

print(x[-1]) # Prints the last entry

[0, 1]
[2, 3, 4, 5]
5


$\textbf{References}$

In [15]:
x = [1,2,3] # Iniate a list 
y = x # Create a new variable name for the list
y[-1] = 4 # Change the last entry of the list 
print(x) 

[1, 2, 4]


$\textbf{More on references}$

To ensure that modifications to the variable y do not affect x, it's necessary to create a copy of x and assign it to y.
This way, y becomes an independent entity, allowing changes to be made to y without altering x

In [16]:
x = [1, 2, 3] # Define a list
y = x.copy() # Define a variable y which copies the list of x


y[-1] = 4 # Alter the last entry of y

# print x
print(x)

# print y
print(y)

[1, 2, 3]
[1, 2, 4]


$\textbf{Loops - Break}$

In [ ]:
# Define a range, a range starts a 0 with stepsize 1 if not specified
for i in range(5):
    
    # if i is more or equal to the third element in the range break
    if i >= 2: break

    # while i is less than the third element print i
    print(i)

0
1


$\textbf{Loops - Continue}$

In [19]:
# Define a range, starts a 0 with stepsize 1 if not specified
for i in range(5):
    
    # If i is equal to 2 end the current iteration and move on to the next
    if i == 2: continue
    
    # While i is not 2 print i
    print(i)

0
1
3
4


$\textbf{Conditional(Known as IF-statements)}$

In [25]:
# Define a variable x and set it equal to 3
x = 3

# Create an IF-statement
if x > 3:
    print('too big')
elif x < 1:
    print('too small')
else:
    print('just right')

just right


$\textbf{Functions and scope}$

In [27]:
a = 1
def f(x):
    return x+a # a is global variable
def g(x,a=1):
    return x+a # a is local variable (Stronger condition and safer)
print(f(1))
print(g(1))

a = 2
print(f(1))
print(g(1))


2
2
3
2


$\textbf{Numpy}$

In [ ]:
import numpy as np              # Import NumPy library

x = np.array([1, 2, 3])         # Create a NumPy array 
y = x                           # y references the same array as x

x += 1                          # In-place addition: x becomes [2 3 4]
print(y)                        # y shows [2 3 4] since it shares the array

x[:] = x + 1                    # In-place update: x becomes [3 4 5]
print(y)                        # y shows [3 4 5] (same object as x)

x = x + 1                       # New array created: x becomes [4 5 6]
print(y)                        # y still points to old array [3 4 5]

[2 3 4]
[3 4 5]
[4 5 6]


$\textbf{Classes}$

In [ ]:
# Define a class named SquareClass to represent squares.
class SquareClass:
    # The __init__ method is a special method called a constructor. It is automatically
    # invoked when a new instance of the class is created. The purpose of this method
    # is to initialize the newly created object's state.
    def __init__(self, length, width):
        # `self` represents the instance of the class. It is the first argument to the
        # methods of a class. Using `self`, we can access the attributes and methods of
        # the class in Python. It binds the attributes with the given arguments.
        
        # `self.length` and `self.width` are instance variables. They are being
        # initialized with the values passed to the __init__ method upon the object's
        # creation. This allows each instance of SquareClass to have its own length and
        # width values.
        self.length = length
        self.width = width
    
    # This is an instance method that calculates and returns the area of the square.
    # Instance methods need a reference to the specific object instance (self) to access
    # its attributes and other methods. This method uses `self.length` and `self.width`
    # to access the square's length and width that were stored in the instance variables
    # when the object was instantiated.
    def size(self):
        return self.length * self.width

# Creating an instance (object) of the SquareClass. This action calls the __init__ method
# of SquareClass with `length=2` and `width=2`, initializing the new square object's
# attributes with these values. The variable `square` now refers to this new object.
square = SquareClass(2, 2)

# Print the area of the square. This calls the size method of the object referred to by
# `square`, which calculates the area based on the object's length and width attributes.
print(square.size())

$\textbf{Lets try CoPilot!}$

In [ ]:
import numpy as np
x = np.array ([2,5,10,2,4])
# sort and print
